# Generated by Django 4.0.2 on 2022-02-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True)
                ),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'created',
                    models.DateTimeField(auto_now_add=True)
                ),
                (
                    'description',
                    models.TextField()
                ),
                (
                    'cost',
                    models.DecimalField(decimal_places=2, max_digits=7)
                ),
                (
                    'receipt',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='receipts.receipt'
                    )
                ),
            ],
        ),
    ]
